
\paragraph{Allgemeine Bewertungskriterien.}
Die folgenden Kriterien werden erwartet:
\begin{description}
	\item[Autor:innen.]
	Alle Autor:innen des Dokuments sind namentlich genannt.
 
	\item[Eigene Arbeit.]
	Alle Regeln zum Zusammenarbeiten bei \emoji{star}-Aufgaben wurden befolgt.

	\item[Rechtschreibung und Grammatik.]
	Der Text ist annähernd fehlerfrei, und durchgehend in grammatikalisch korrekten und ganzen Sätzen geschrieben. \emph{If you prefer to submit your solutions in English, \textbf{please do so}.}

	\item[Struktur.]
	Der Text ist in nachvollziehbarer und zielgerichteter Weise strukturiert.
	Die Lösung zu einer Algorithmenaufgabe ist typischerweise wie folgt strukturiert:
	\begin{enumerate}
		\item Grobe Idee: Zunächst wird die Idee des Algorithmus \emph{in wenigen Worten} beschrieben.
		\item Formale Beschreibung: Der Algorithmus wird in natürlicher Sprache, Pseudocode, oder Code präzise und eindeutig beschrieben.
		\item Korrektheitsbeweis: Die Korrektheit des Algorithmus wird bewiesen.
		\item Laufzeitanalyse: Die Laufzeit des Algorithmus wird analysiert.
	\end{enumerate}
	Insbesondere sollten diese vier Aspekte klar getrennt sein und nicht ineinander fließen.
	
	\item[Korrektheit.]
	Der Text enthält keine Widersprüche oder unzulässigen Folgerungen.

	\item[Leserliche Handschrift.]
	(falls relevant) Die Handschrift ist durchgehend ohne Mühe lesbar.

	\item[Mathematik.]
	Mathematische Ausdrücke sind korrekt gesetzt (z.B. $n^2$ anstatt \verb|n^2|) und die mathematischen Ausdrücke sind grammatikalisch korrekt in die Satzstruktur eingebettet.

	\item[Wissenschaftssprache.]
	Der sprachliche Ausdruck ist sachorientiert mit treffender Wortwahl und präzisen Formulierungen. Fachbegriffe werden einheitlich, präzise und auf den Inhalt der Kurses bezogen verwendet.
\end{description}
