
\paragraph{Anforderungen an schriftliche Abgaben.}
In der Klausur gibt es zum Bestehen notwendige \mittel-Aufgaben, in denen du die Korrektheit und die Laufzeit eines Algorithmus beweisen musst.
In den schriftlichen Abgaben übst du, wie man das richtig macht. Es gibt bewusst nur eine schriftliche Aufgabe pro Woche, damit du dich intensiv mit dem Schreiben beschäftigen kannst. Achte hierbei auf die folgenden Aspekte:
\begin{description}
	\item[Autor:innen.]
	Alle Autor:innen des Dokuments sind namentlich genannt.

	\item[Schreibstil.]
	Dein Text sollte durchgehend in grammatikalisch korrekten und ganzen Sätzen geschrieben sein.
	Achte darauf, dass alle Sätze möglichst kurz sind und keine zu verschachtelten Nebensätze enthalten. Wissenschaftssprache ist dann am besten, wenn sie stilistisch gesehen \emph{einfach} ist. \emph{If you prefer to submit your solutions in English, \textbf{please do so}.}

	\item[Struktur.]
	Dein Text muss nachvollziehbar und zielgerichtet strukturiert sein.
	Die Lösung zu einer Algorithmenaufgabe ist typischerweise wie folgt strukturiert:
	\begin{enumerate}
		\item Grobe Idee: Zunächst beschreibst du in einer \textbf{kurzen} Einleitung die Idee des Algorithmus in natürlicher Sprache auf. Ein kurzer Absatz genügt in den meisten Fällen.
		\item Formale Beschreibung: Du beschreibst den Algorithmus in Pseudocode oder Code.
		\item Korrektheitsbeweis: Du beweist die Korrektheit des Algorithmus.
		\item Laufzeitanalyse: Du analysierst die Laufzeit des Algorithmus.
	\end{enumerate}
	Insbesondere sollten diese vier Aspekte klar getrennt sein und nicht ineinander fließen.

	\item[Korrektheit und Präzision.]
	Dein Text darf keine Widersprüche oder unzulässigen Folgerungen beinhalten, er muss stets präzise und eindeutig sein. \textbf{Stell dir bei jedem Satz die Frage, wie ein Leser ihn missverstehen könnte, und formuliere den Satz so lange um, bis keine Missverständnisse mehr möglich sind.}
	
	\item[Zielorientiert.]
	Dein Text muss durchgehend zielgerichted und kompakt sein. Stell dir bei jedem Satz die Frage, ob er nicht doch weg gelassen oder gekürzt werden kann.
	Irrelevante Ausführungen führen in der Klausur selbst dann zu Punktabzug, wenn sie nicht falsch sind.

	\item[Leserliche Handschrift.]
	(falls relevant) Die Handschrift ist durchgehend ohne Mühe lesbar.

	\item[Mathematik.]
	Mathematische Ausdrücke sind korrekt gesetzt (z.B. $n^2$ anstatt \verb|n^2|) und die mathematischen Ausdrücke sind grammatikalisch korrekt in die Satzstruktur eingebettet.

	\item[Wissenschaftssprache.]
	Der sprachliche Ausdruck ist sachorientiert mit treffender Wortwahl und präzisen Formulierungen. Fachbegriffe werden einheitlich, präzise und auf den Inhalt der Kurses bezogen verwendet.
\end{description}
